### PR TITLE
CP-1320 Release dart_to_js_script_rewriter 1.0.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1320

JIRA and PR's included in this release: 

 CP-1328  - Move dart_to_js_script_rewriter to workiva ownership  - https://github.com/Workiva/dart_to_js_script_rewriter/pull/28
 CP-1336  - kasperpeulen: make sure that transformer only touches file that need to be rewritten  - https://github.com/Workiva/dart_to_js_script_rewriter/pull/29
 CP-1355  - Create COPYRIGHT_TRANSFER  - https://github.com/Workiva/dart_to_js_script_rewriter/pull/31

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_to_js_Script_rewriter/compare/master...CP-1320_release_1.0.0

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1 to entire code base

**Comment by maxwellpeterson-wf** [comment]
+1 to entire codebase

**Comment by dustinlessard-wf** [comment]
+1 to entire codebase

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
