### PR TITLE
CP-1395 Correct pub publish updates

### PR DESCRIPTION
**Pull request by jayudey-wf**
## Issue
- I wasn't able to publish to pub because the pubspec.yaml had an in-correct field

## Changes
**Source:**
- referenced authors instead of author

**Tests:**
- n/a

## Areas of Regression
- n/a

## Testing
- verify `pub publish --dry-run` results in no warnings

## Code Review
@trentgrover-wf
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+10 
- Ran `pub publish --dry-run` and there were no warnings.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - performed and documented by Evan
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
