### PR TITLE
HY-4965 Turn on strong mode and 2 lint rules

### PR DESCRIPTION
**Pull request by robbecker-wf**
This turns on strong mode and adds 2 lint rules to make sure streams are closed.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by smaifullerton-wk** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+10
- CI passes

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Tests created/updated 
  - Tooling only
- [x] All tests pass

@Workiva/release-management-pp

**Pull request merged**
