### PR TITLE
CP-2697 update dependencies

### PR DESCRIPTION
**Pull request by kevmoo**
update dependencies

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by trentgrover-wf** [comment]
+1
@maxwellpeterson-wf @evanweible-wf @dustinlessard-wf @sebastianmalysa-wf @jayudey-wf

**Comment by rm-astro-wf** [comment]
Sorry, I could not create a JIRA ticket for this pull.

I sent the following data to JIRA:
`{'issuetype': {'name': None}, 'project': {'key': u'CP'}, 'description': '', 'components': [], 'summary': 'update dependencies'}`

I received the following data from JIRA:
`Hidden on Open Source Repos`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by evanweible-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by kevmoo** [comment]
Guys: the new review thing is super nice. 😄 

https://help.github.com/articles/approving-a-pull-request-with-required-reviews/

**Comment by maxwellpeterson-wf** [comment]
@kevmoo we can't use it until our internal systems support it (mostly for tracking our SOC1 compliance), but I agree it is great!

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction (derived from offline discussion)
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Comment by kevmoo** [comment]
Thanks, ya'll!

Publish?

**Comment by jayudey-wf** [comment]
Published, https://pub.dartlang.org/packages/dart_to_js_script_rewriter

Thanks again!

**Pull request merged**
