### PR TITLE
CP-1394 Release dart_to_js_script_rewriter 1.0.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1394

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

 CP-1395  - Correct pub publish updates  - https://github.com/Workiva/dart_to_js_script_rewriter/pull/33

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_to_js_script_rewriter/compare/1.0.0...CP-1394_release_1.0.1

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
