### PR TITLE
CP-2938 Adding smithy.yaml

### PR DESCRIPTION
**Pull request by jayudey-wf**
## Issue
- We needed to add a smithy.yaml for release management to more easily track dependencies.

## Changes
**Source:**
- Included smithy.yaml

**Tests:**
- n/a

## Areas of Regression
- passing CI's

## Testing
- passing CI

## Code Review
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf
@sebastianmalysa-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by rmconsole2-wf** [comment]
Sorry, I could not create a JIRA ticket for this pull.

I sent the following data to JIRA:
`{'issuetype': {'name': None}, 'project': {'key': u'CP'}, 'description': "## Issue\r\n- We needed to add a smithy.yaml for release management to more easily track dependencies.\r\n\r\n## Changes\r\n**Source:**\r\n- Included smithy.yaml\r\n\r\n**Tests:**\r\n- n/a\r\n\r\n## Areas of Regression\r\n- passing CI's\r\n\r\n## Testing\r\n- passing CI\r\n\r\n## Code Review\r\n@maxwellpeterson-wf\r\n@evanweible-wf\r\n@dustinlessard-wf\r\n@sebastianmalysa-wf ", 'components': [], 'summary': 'Adding smithy.yaml'}`

I received the following data from JIRA:
`Hidden on Open Source Repos`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by rmconsole3-wf** [comment]
Sorry, I could not create a JIRA ticket for this pull.

I sent the following data to JIRA:
`{'issuetype': {'name': None}, 'project': {'key': u'CP'}, 'description': "## Issue\r\n- We needed to add a smithy.yaml for release management to more easily track dependencies.\r\n\r\n## Changes\r\n**Source:**\r\n- Included smithy.yaml\r\n\r\n**Tests:**\r\n- n/a\r\n\r\n## Areas of Regression\r\n- passing CI's\r\n\r\n## Testing\r\n- passing CI\r\n\r\n## Code Review\r\n@maxwellpeterson-wf\r\n@evanweible-wf\r\n@dustinlessard-wf\r\n@sebastianmalysa-wf ", 'components': [{'name': u'dart_to_js_script_rewriter'}], 'summary': 'Adding smithy.yaml'}`

I received the following data from JIRA:
`Hidden on Open Source Repos`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by charliekump-wf** [comment]
+10 Smithy valid and runs successfully.

**Comment by charliekump-wf** [comment]
Quality Review Approval: +1

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Unit test created/updated - N/A
- [x] All unit tests pass 

Merging into master.

**Pull request merged**
